Feature/scroll navigation
ConstructiveNews/squirrel-news-app pull request #63
Opened 2023-01-11 15:35 UTC by hstaatsxx

2023-01-16 17:08 UTC, DevJacobi commented on src/pages/SettingsPage.tsx
> +    history.push('/')
All the other options do not push us to the main menu when we update a setting. I think we should not do that here

2023-01-16 17:09 UTC, DevJacobi requested changes
Great work 🎉 
Just a minor remark

2023-01-16 17:42 UTC, hstaatsxx commented on src/pages/Swiperview.tsx
> +                pagination={{ clickable: true, enabled: swipe === SWIPE.HORIZONTAL ? true : false }} modules={[Pagination]}>
okay, now it works. funny :D

2023-01-18 12:23 UTC, DevJacobi approved these changes

2023-01-18 12:23 UTC, merged

2023-01-18 12:27 UTC, DevJacobi commented
Tested

https://user-images.githubusercontent.com/43578928/213171335-7ad9c25d-c6f6-4931-a2b2-8b9c9c30b9f6.mp4